/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Row ID]
      ,[Order ID]
      ,[Order Date]
      ,[Ship Date]
      ,[Ship Mode]
      ,[Customer ID]
      ,[Customer Name]
      ,[Segment]
      ,[Postal Code]
      ,[City]
      ,[State]
      ,[Country]
      ,[Region]
      ,[Market]
      ,[Product ID]
      ,[Product Name]
      ,[Sub-Category]
      ,[Category]
      ,[Sales]
      ,[Quantity]
      ,[Discount]
      ,[Profit]
      ,[Shipping Cost]
      ,[Order Priority]
      ,[DaysToShipScheduled]
      ,[DaysToShipActual]
      ,[ShippingStatus]
  FROM [SALE_DB].[dbo].[ShippingStatus]